### ISSUE TITLE
Implement Grenadier enemy

### ISSUE THREAD

**Issue by Sirkular** [MaXeraph/Adrenarun#14]
The Grenadier’s basic movement consists of chasing after the player up to a certain distance and then firing projectiles at the player, which explode on impact, igniting the ground for a set duration afterwards. We intend for this to encourage players to move around, rather than remain in a certain position.
The two targeting behaviours that the Grenadier will be able to have consist of Direct and Predictive Targeting. 
There will be no subtypes for the Grenadier.
This enemy will spawn on ground level or at a higher position than the player, to allow for maximal coverage of the area surrounding the grenadier.

**Comment by ethanakester** [comment]
https://github.com/MaXeraph/Adrenarun/pull/52
https://github.com/MaXeraph/Adrenarun/pull/50
