### ISSUE TITLE
Implement Grounded Ranged enemy

### ISSUE THREAD

**Issue by Sirkular** [MaXeraph/Adrenarun#15]
The Grounded Ranged enemy’s basic movement consists of chasing after the player up to a certain distance and then firing projectiles at the player. 
The three targeting behaviours that the Grounded Ranged will have consist of Direct Targeting, Predictive Targeting, and Set Targeting. These will lead to simple, yet diverse interactions with the player.
The subtypes we will be implementing for the Grounded Ranged Enemy consist of the “Regular” behaviour, where one projectile is shot at a consistent rate, to serve as our standard and most common occurrence of this enemy, and the “SMG” and “Shotgun” subtypes that will serve as a challenge to the player as they progress. [This does not need to be implemented currently, however, the framework needs to accommodate subtypes.] 
This enemy will spawn at ground level, being on even footing with the player.

**Comment by ethanakester** [comment]
https://github.com/MaXeraph/Adrenarun/pull/57
